services:
  mongodb:
    image: mongo:8.0
    container_name: megabot_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=megabot_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./docker/mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js
      - ./docker/data:/docker/data

volumes:
  megabot_mongodb_data: